### ISSUE TITLE
Major bug? Integer division instead of floating point in weight calculation.

### ISSUE THREAD

**Issue by ANogin** [RalfRothenberger/Power-Law-Random-SAT-Generator#3]
Your code computes `VWeights[i]=pow((variables/(i+1)),betaNorm)` using integer division. As a result, the weights do not match the intended weights in your paper. E.g. I generated 10000 instances using your generator with `-g p -v 15 -c 65 -n 10000 -u 1` arguments, and here are the variable counts:
```
 321607 1
 228282 2
 194102 3
 149418 5
 149233 4
 121197 6
 120637 7
  83570 10
  83365 8
  83361 14
  83254 9
  83191 12
  83098 15
  82994 11
  82691 13
```
starting with `i+1=8`, `variables/(i+1)` is `1`, which is why the counts are about the same for variables 8 though 15...

Unless I am missing something, I am guessing this potentially invalidates the experimental results from your papers using the code?

**Comment by RalfRothenberger** [comment]
Hi,
you are right, this is a bug and I am going to fix it as soon as possible.

It should not have much of an influence on the experimental results, since the resulting weight differences are minor. However, I will run some new experiments and report if any big changes come up.

Thank you for reporting that issue!

**Comment by RalfRothenberger** [comment]
Hey, I just uploaded the corrections.

**Comment by ANogin** [comment]
@RalfRothenberger , I do not know how significantly this bug affects the end results, but in term of weights, with this bug the effective weights end up in about x.75 .. x1.1 range of what they were supposed to be.

P.S. The "unique" requirement also skews things a bit (the distribution with -u 0 follows the expected weights, once this bug and #4 are fixed, but the distribution with `-u 1` is a bit off as the "rerolling" on a clash skews it - more so with smaller # of variables).

**Comment by ANogin** [comment]
Unless I messed up something, with beta of 2.5 and 1000 variables, for 3-SAT with power-law generator, the critical clause count was about 2245 clauses with the bug, and 2541 after the bug fix, so the difference appears to be pretty substantial.

**Comment by RalfRothenberger** [comment]
Hmmm...you might be right. But at least with increasing number of variables the difference should vanish. I am running new experiments at the moment and will report as soon as I recreated the experiments from the papers. At the end of next week latest. However, I actually expect the new experimental results to be even more in line with the theoretical ones now.
